# Generated by Django 4.2.17 on 2024-12-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=50)),
                ('category_type', models.CharField(max_length=20)),
                ('creation_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Product Category',
            },
        ),
    ]
