# Generated by Django 4.2.17 on 2024-12-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleserp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=250)),
                ('category_id', models.IntegerField(editable=False)),
                ('year', models.DateField(editable=False)),
                ('price', models.FloatField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('last_updated_user', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='productcategory',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
