# Generated by Django 4.2.17 on 2024-12-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleserp', '0002_products_productcategory_last_updated_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
